### ISSUE TITLE
APIs-To-Be-Implemented Tracker

### ISSUE THREAD

**Issue by IsaacMarovitz** [IsaacMarovitz/SharpMetal#1]
# SharpMetal Hit-List: 
- [x] MTLCommandQueue
- [x] MTLCommandBufferDescriptor
- [x] MTLCompileOptions
- [x] MTLSamplerDescriptor
- [x] MTLCommandBuffer
- [x] MTLDispatchType
- [x] MTLDevice
- [x] MTLBlitPassDescriptor
- [x] MTLResourceStatePassDescriptor
- [ ] MTLRenderCommandEncoder
- [ ] MTLParallelRenderCommandEncoder
- [ ] MTLBlitCommandEncoder
- [ ] MTLComputeCommandEncoder
- [ ] MTLComputePassDescriptor
- [ ] MTLResourceStateCommandEncoder
- [ ] MTLViewport
- [ ] MTLCommandBufferHandler
- [ ] MTLDrawable
- [ ] MTLEvent
- [ ] MTLLogContainer

## Acceleration
- [x] MTLAccelerationStructureUsage
- [x] MTLAccelerationStructureRefitOptions
- [x] MTLAccelerationStructureInstanceOptions
- [x] MTLAccelerationStructurePassDescriptor
- [x] MTLAccelerationStructurePassSampleBufferAttachmentDescriptorArray
- [x] MTLAccelerationStructurePassSampleBufferAttachmentDescriptor
- [ ] MTLAccelerationStructureCommandEncoder
- [ ] MTLAccelerationStructure
- [ ] MTLPrimitiveAccelerationStructureDescriptor
- [ ] MTLInstanceAccelerationStructureDescriptor
- [ ] MTLAccelerationStructureTriangleGeometryDescriptor
- [ ] MTLAccelerationStructureBoundingBoxGeometryDescriptor
- [ ] MTLAccelerationStructureMotionTriangleGeometryDescriptor
- [ ] MTLAccelerationStructureMotionBoundingBoxGeometryDescriptor
- [ ] MTLMotionKeyframeData
- [ ] MTLAccelerationStructureInstanceDescriptor
- [ ] MTLAccelerationStructureUserIDInstanceDescriptor
- [ ] MTLAccelerationStructureMotionInstanceDescriptor
- [ ] MTLIntersectionFunctionTable
- [ ] MTLIntersectionFunctionTableDescriptor
- [ ] MTLAccelerationStructureDescriptor
- [ ] MTLAccelerationStructureGeometryDescriptor
- [ ] MTLIntersectionFunctionSignature
- [ ] MTLAxisAlignedBoundingBox
- [ ] MTLPackedFloat3
- [ ] MTLPackedFloat4x3
- [ ] MTLPackedFloat3Make

## Non-Metal
- [ ] NSError
- [ ] CFTimeInterval
- [ ] MetalFX
- [ ] MetalKit
- [ ] Metal Performance Shaders
- [ ] Metal Performance Shaders Graph

**Comment by lqj01** [comment]
Why was this issue closed? 😭Was it because there is a better solution available?😄 I'm also looking forward to the integration of native Metal. I got really excited when I saw that you were working on this task. I've been following your progress since the beginning. With this question, I also want to know if you have encountered any difficulties at the moment.

**Comment by IsaacMarovitz** [comment]
> Why was this issue closed? 😭Was it because there is a better solution available?😄 I'm also looking forward to the integration of native Metal. I got really excited when I saw that you were working on this task. I've been following your progress since the beginning. With this question, I also want to know if you have encountered any difficulties at the moment.

I working on a generator for bindings instead of building them all manually. You can see the progress on that effort here https://github.com/IsaacMarovitz/SharpMetal/tree/master/SharpMetal.Generator
