### ISSUE TITLE
Avalonia Sample

### ISSUE THREAD

**Issue by Noemata** [IsaacMarovitz/SharpMetal#8]
Any chance of getting a sample that combines your lib with Avalonia?  I was hoping to have something similar to a Swapchainpanel that facilitates wiring shader params to C# properties.

**Comment by IsaacMarovitz** [comment]
The example projects provide information on writing data to MTLBuffers from C# at runtime. Avalonia should really not be much of a complication; Bind an Avalonia control to the C# property you later encode to the MTLBuffer and redraw whenever the value changes, if you're doing retained-mode style rendering, or just let the new frame come by and encode the value if you're doing something immediate mode.

**Comment by IsaacMarovitz** [comment]
If you mean embedding a SharpMetal-backed context in an Avalonia UI that's a little more complicated and not something I plan to provide an example for.

**Comment by Noemata** [comment]
Yes, that is what I meant.  Indeed, it's a tricky problem.  What can I say, a free lunch is always appealing.
